-- 2023 기출문제 03회

-- 8. 다음 <SQL>을 모두 실행하였을 때 검색 결과를 작성하시오.
CREATE TABLE Table_A(COL1 INTEGER, COL2 INTEGER);
CREATE TABLE Table_B(COL1 INTEGER, COL2 INTEGER);

INSERT INTO Table_A(COL1, COL2) VALUES (1, 2);
INSERT INTO Table_A(COL1, COL2) VALUES (1, 2);
INSERT INTO Table_A(COL1, COL2) VALUES (1, 3);

INSERT INTO Table_B(COL1, COL2) VALUES (1, 2);
INSERT INTO Table_B(COL1, COL2) VALUES (1, 4);
INSERT INTO Table_B(COL1, COL2) VALUES (1, 5);

SELECT DISTINCT COL1, COL2 FROM Table_A
UNION
SELECT COL1, COL2 FROM Table_B ORDER BY COL2 DESC;